### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by Shohreh** [cyclosm/cyclosm-website#14]
Hello,

Things I miss:
- Marker to show a location à la https://www.openstreetmap.org
- Use cookie to open the site by zooming either on the user's home location or the last location visisted
- Let the user choose whether to see the right-side banner instead of showing it every time
- The bike shop icon is too small: Make it bigger à la OpenCycleMap.

Cheers,

**Comment by Florimondable** [comment]
Hi,

 
>     * Marker to show a location à la https://www.openstreetmap.org
What do you mean by a marker like on osm.org ? The note ?
 
>     * Use cookie to open the site by zooming either on the user's home location or the last location visisted
Last location is already the case.

>     * Let the user choose whether to see the right-side banner instead of showing it every time
Agreed!
 
>     * The bike shop icon is too small: Make it bigger à la OpenCycleMap.
Yes, but that’s a ticket for the style itself https://github.com/cyclosm/cyclosm-cartocss-style

Thanks for your ideas.
