### ISSUE TITLE
Waymarkedtrails Link

### ISSUE THREAD

**Issue by quasart** [cyclosm/cyclosm-website#17]
Hello and thank you again for this project !

I noticed Waymarkedtrails layer credit links to wrong url. Obviously, this is the href to change :

https://github.com/cyclosm/cyclosm-website/blob/82127a491c098910208960a1c68bb5d60de27cfd/index.html#L291

**Comment by Phyks** [comment]
Hi!

Fixed and deployed. Thanks for the report!
