### ISSUE TITLE
Main Cycleosm layer delay for high zoom levels

### ISSUE THREAD

**Issue by Jasskurn** [cyclosm/cyclosm-website#19]
For several day, it appears, the main Cyclosm layer is only "live generated" for level 20,  Information page indicates "live generated" should apply for zoom levels above 11.  Same applies for new layer named "CyclOSM (Live)". CyclOSM Lite does appear to live generate.

Can not see issue in linked to Munin page

Temporary issue? or the information page needs to be updated regarding live updates

**Comment by Phyks** [comment]
Indeed, we are currently having active work on our hosting infrastructure (OSM-France) to be able to serve CyclOSM to a wider range of people.

As such, the current text is outdated and we are:
- always pre-generated (weekly job) for zooms 1 through 11.
- for the "cyclosm live" style, we are having live rendering, mainly targeted for contributors. This style should have few minutes latency, as it used to be for CyclOSM.
- for the regular "cyclosm" style, this is the style meant to be used by the wider range of customers and there is an additional layer of caching in front. Thus, the tiles might be up to 72 hours old (in practice, they should be about 24 hours old max).

I'm closing this one in favor of #20 to track the need for an additional info message.
