### ISSUE TITLE
[suggestions] Marker ; Bigger icons for bike shops

### ISSUE THREAD

**Issue by Shohreh** [cyclosm/cyclosm-website#21]
Hello,

I have two suggestions:

1. Add a marker like on OSM.org as a way to share a location

2. Make the bike shops bigger, à la OpenCycleMap. The current icons are so small as to be useless when browsing an area looking for bike shops

Cheers,

**Comment by Phyks** [comment]
1. So far cyclosm.org does not aim at being a full featured map client as could be osm.org or others. If you can write a pull request to add support for the feature, please feel free to do so and we'll happily merge it. We will likely not develop it ourselves though. Also note that CyclOSM is in the process of being added onto osm.org and widely available in BRouter-web, both services offering a carefully designed and full featured interface.

2. This should be a dedicated issue in https://github.com/cyclosm/cyclosm-cartocss-style/ (the repository about the actual map style code, not the web demonstration).
