### ISSUE TITLE
Legend doesn't have coral-pink road

### ISSUE THREAD

**Issue by soshial** [cyclosm/cyclosm-website#24]
![image](https://user-images.githubusercontent.com/100644/116811202-0e94bd80-ab59-11eb-942e-e1b06f01cbde.png)

Legend does not mention such color at all: https://www.cyclosm.org/legend.html

**Comment by Phyks** [comment]
These are bicycle=no roads, we'll add it to the legend.

**Comment by soshial** [comment]
Isn't it the same as grey color "bycicle not allowed"?

**Comment by Florimondable** [comment]
Bicycle not allowed is grey, and the key "Motorway, Trunk" should be coral-pink.
It’s a mistake in the legend because we use to have motorway only in grey, now it’s by default in grey unless bicycle is allowed, in this case we render in coral-pink.

**Comment by Phyks** [comment]
Fixed in legend.
