### ISSUE TITLE
Could I use your tiles in uNav?

### ISSUE THREAD

**Issue by costales** [cyclosm/cyclosm-website#26]
Hi,

I developed a GPS navigator and map viewer for Ubuntu Touch (https://ubports.com). Currently, It doesn't so much users. It is free under GPL license.

Please, could I include your tiles map in this app? https://unav.me It wouldn't be the default map, just if the user choose from the settings a map for biciclist.

Thanks in advance!

**Comment by Phyks** [comment]
Hi,

Our tiles are available under a fair use policy, similar to the one for osm.org tiles: https://operations.osmfoundation.org/policies/tiles/.

Basically, you are free to use them as you like as long as:

1. You have a fair-use of the tiles (no sequential downloads, no huge user base). This seems fine from what you say about your app.
2. Your app can be easily identified and we have a mean to reach out in case of issues / disruptions. The best way to do this is to ensure your app sends a meaningful User-Agent header string.

Best,
