### ISSUE TITLE
Map currently down

### ISSUE THREAD

**Issue by limex** [cyclosm/cyclosm-website#27]
First: Thanks for your great work!
The issue: https://www.cyclosm.org/#map=14/46.9987/15.0029/cyclosm is down als the tiles are not loading.

Thanks in advance.

**Comment by michaelblyons** [comment]
Map is down again, both your own and the OSM.org layer.

**Comment by Phyks** [comment]
https://github.com/cyclosm/cyclosm-cartocss-style/issues/608

**Comment by michaelblyons** [comment]
Thanks. I checked the open cartocss tickets, but didn't check the closed ones there.
