### ISSUE TITLE
Mapnik greyscale layer

### ISSUE THREAD

**Issue by afranke** [cyclosm/cyclosm-website#36]
https://www.openrailwaymap.org/ offers a greyscale layer by default and it’s just so much more readable than any of the colour ones currently on CyclOSM. The colours used for forests, mountains and others clash against the bicycle paths and make things look way busier than they really are.

Compare for example (both at zoom level 10, 48.5180 latitute, 8.0269 longitude)

![image](https://github.com/cyclosm/cyclosm-website/assets/117241/13c0bc05-62a3-4a70-9d33-bd8da92bf2ee)

to

![image](https://github.com/cyclosm/cyclosm-website/assets/117241/2b604c6f-1571-4f0c-8f63-02bcc9bc076a)

or (zoom 13, 48.5500 lat, 7.8000 lon)

![image](https://github.com/cyclosm/cyclosm-website/assets/117241/2e168e45-75c9-499e-8718-2a9e5618718b)

to

![image](https://github.com/cyclosm/cyclosm-website/assets/117241/f8320ce9-f0c8-4079-8836-84769b573901)

The cycle paths are indeed actually busier than the train tracks… which is all the more reason to use a more subdued background!

The orange bike path in the green mountain on the left on the first CyclOSM screenshot is also quite difficult for me to see, with my *mild* colour blindness (deuteranomaly). The greyscale background would help with accessibility.

**Comment by quasart** [comment]
I agree the colour palette can be improved:
Water areas shade is very close to low speed roads

**Comment by Phyks** [comment]
OpenRailwayMap is quite different from CyclOSM. At least from two perspectives:
1/ OpenRailwayMap only displays railways while CyclOSM (despite the name) provides both a cycle and outdoor map (at least, this is the two populations of heavy users we have)
2/ OpenRailwayMap is an overlay map, generating transparent tiles/geometries over a base layer.

I agree that the black and white background makes cycle routes stand out. However, this is at the expense of the outdoor aspect, making it very difficult to distinguish water vs forests vs ...

So, we could slightly tune the colors (make them more fade, etc.) but moving to a full greyscale + overlay style is too much of a change for CyclOSM.

**Comment by afranke** [comment]
I didn’t ask to make this the default or to get rid of the existing presentation. I asked to offer this. Several other presentations are already available, why not add this to the list?

**Comment by Phyks** [comment]
Problem is that CyclOSM codebase + infra generates raster tiles (static images, single image per location). This is different from Mapbox (vector tiles) or OpenRailwayMap (overlay, that is semi-transparent images displayed on top of a base layer).

Therefore, CyclOSM style is all or nothing (cycle tracks + base map), and not easily customisable.

EDIT : This is a bit of work, but we could probably offer it in the codebase. However, this is quite a significant change in hosting and serving the tiles which cannot be done so easily (tldr, it is easy to code it, it is difficult to distribute it).

**Comment by Florimondable** [comment]
On [CyclOSM.org](https://www.cyclosm.org) we have a "lite" layer with only cycling infrastructure (track, lane, ...) and no background, you can also add the WayMarkedTrail layer, and choose piano for a white&black background, and you’ll get something close to what your looking for : 
[https://www.cyclosm.org/#map=13/48.5404/7.7438/piano-waymarkedtrails-cyclosmlite](https://www.cyclosm.org/#map=13/48.5404/7.7438/piano-waymarkedtrails-cyclosmlite)

This lite style is old and no more up to date, though it’s generate up to date tiles.
